### ISSUE TITLE
Multiple/evolving relationships between same people

### ISSUE THREAD

**Issue by gaetanmuck** [geovistory/switzerland-and-beyond#11]
How to model the 2 following situations:

1/ Two persons have had a relationship, ended it, and get back together. It is two different relationships? Or is it the same one that was "reopen"? Also for friendship, mentorship, ...

2/ When two persons have a relationship together, and after 1 year they get married. Is it two different relationships? Or it is the same one that evolved? More generally how to model evolving relationships?

@atterebf 
@stephenhart8

**Comment by stephenhart8** [comment]
Hi Gaétan,

In both cases, I would suggest that it's two different relationships, as the essence of the relationship is different:
- In the first case, the relationships have a different time-span (otherwise with just one relationship we would have to join both time-span together, not documenting the separation).
- In the second case, the nature of the relationship changes, from a non-marital to a marital relationship, which has huge impact socially (with a marital contract, obligations, etc.)
